#!/bin/sh


dir=$HOME/git/commitbeat
d=`date +%s`
file=$dir/git-$d

wg() {
	wget -O $file "https://api.github.com/events?client_id=0359bad16f57c858d3ec&client_secret=da620e158454bae03538ac45b91ce3aeeb791495"
}

debug() {
	echo "$@" 1>&2
}

# new
if ! [ -e $file ]; then
	debug "Polling github..."
	wg
	cat $file
fi
